# Generated by Django 4.2.4 on 2023-08-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('intro', models.CharField(max_length=300, verbose_name='Описание проблемы')),
                ('full_text', models.TextField(verbose_name='Решение проблемы')),
                ('date', models.DateTimeField(verbose_name='Дата появление вопрос')),
            ],
        ),
    ]
